# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: nice_nano_v2
    shield: cornix_dongle_adapter cornix_dongle_eyelash dongle_display
    snippet: studio-rpc-usb-uart nrf52840-nosd
    artifact-name: cornix_dongle_nosd

  - board: cornix_left
    #shield: cornix_indicator
    artifact-name: cornix_left_default_nosd

  - board: cornix_ph_left
    #shield: cornix_indicator
    artifact-name: cornix_left_for_dongle_nosd

  - board: cornix_right
    #shield: cornix_indicator
    artifact-name: cornix_right_nosd

  - board: cornix_right
    shield: settings_reset
    artifact-name: reset

  - board: cornix_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart nrf52840-nosd
    artifact-name: reset_nosd

  # - board: cornix_e73
  #   shield: cornix_dongle dongle_display
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: cornix_dongle

  # - board: cornix_e73
  #   shield: cornix_main_left
  #   artifact-name: cornix_left_default

  # - board: cornix_e73
  #   shield: cornix_ph_left
  #   artifact-name: cornix_left_for_dongle

  # - board: cornix_e73
  #   shield: cornix_right
  #   artifact-name: cornix_right

  # - board: cornix_e73
  #   shield: settings_reset
  #   artifact-name: reset

  # - board: nice_nano_v2
  #   shield: corne_dongle_pro_micro dongle_display
  #   cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Dongle_O\"
  #   artifact-name: nice_corne_dongle_oled
  #   snippet: studio-rpc-usb-uart

  # - board: nice_nano_v2
  #   shield: corne_left
  #   snippet: studio-rpc-usb-uart
  # - board: nice_nano_v2
  #   shield: corne_right
  # - board: nice_nano_v2
  #   shield: corne_left_peripheral
  #   artifact-name: nice_corne_left_peripheral


  # - board: nice_nano_v2
  #   shield: settings_reset
  #   artifact-name: nice_settings_reset
