manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cornix-shield
      url-base: https://github.com/hitsmaxft
    - name: urob
      url-base: https://github.com/urob
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: hitsmaxft
      url-base: https://github.com/hitsmaxft
    - name: janpfischer
      url-base: https://github.com/janpfischer

    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: abb64ba316c29caddc49727ca2cac2f0ed5970c7
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: 7e0219e170ca2b919a5162412a1e6aa2d7b712aa
    - name: zmk-tri-state
      remote: dhruvinsh
      revision: ebbc1f0ccdb51669650bb0ac3e34920d09e62400
    - name: zmk-keyboard-cornix
      remote: cornix-shield
      revision: v2.6.8
    - name: zmk-rgbled-widget
      remote: hitsmaxft
      revision: f1a8be56d37b88169fff6afc87fb92ad3bc53634
      clone-depth: 1
    - name: zmk-dongle-display
      remote: hitsmaxft
      revision: 379d012702feeb85d7ff89879408283b763dece7
      clone-depth: 1
    - name: zmk-dongle-screen
      remote: janpfischer
      revision: 0.1.2
      clone-depth: 1

  self:
    path: config
